[build]
  command = "npm run build" # the command you run to build this file
  publish = "public" # gatsby builds to this folder, Netlify should serve all these files statically

[[plugins]]
  package = "netlify-plugin-gatsby-cache" # gatsby fast build